### PR TITLE
Handle Charts without an "award" column

### PR DESCRIPTION
**Pull request by cycomachead**
As best I can tell, this really only applies to the current TikTok chart. 

The issue is that the column numbers are off because of the the Nth column of metadata isn't found. 

I handled this by detecting the presence of the award column, and if missing adjusting the column indices down. 

* Haven't added tests.
* Need to adapt this to year end charts, in theory. 

A more stable change would be for all metadata indexing to determine the relative column position but that's probably not necessary.

### CODE REVIEW

**Review by guoguo12 — APPROVED** [review]
Thank you! Seems to work.

**Comment by cycomachead** [comment]
Thanks for the quick pull! :) 

I've been using this in the process of created a DB for use in a [data 101](https://data101.org) assignment which will involve querying chart data.

**Comment by guoguo12** [comment]
Oh, nice, thanks for sharing! I flipped through the sp24 slides and 1) they're beautiful and 2) they seem to cover a broad range of interesting topics :)

**Comment by cycomachead** [comment]
Just in case you're curious. :) Assignment is here! https://github.com/cal-data-eng/fa24-materials/tree/main/proj/proj0 

And I can't take credit for the slides, but we're redoing the template this fall to be even nicer, hopefully. ;)

**Comment by guoguo12** [comment]
Looks fun (and topical)! Thanks for sharing!

**Pull request merged**
